### ISSUE TITLE
Additional POI layers 

### ISSUE THREAD

**Issue by hbruch** [mfdz/digitransit-ui#12]
The following POI layers (extracted from OSM) should be added:

Taxi stand
* nwr[amenity=taxi]

Bicycle infrastructure
* nwr[amenity=bicycle_parking][covered=yes]
* nwr[amenity=bicycle_parking][covered=no]
* nwr[amenity=bicycle_repair_station]
* nwr[shop=bicycle]
* nwr[man_made=monitoring_station]["monitoring:bicycle"="yes"]
* nwr[amenity=charging_station][bicycle=yes]

Parkings
* (nwr[amenity=parking]["access"!="private"]["access"!="customers"];
nwr[amenity=parking]["park_ride"="yes"];);

Charging Infrastructure:
* nwr[amenity=charging_station][car=yes]

Bike/Carsharing locations:
* nwr[amenity=bicycle_rental]
* nwr[amenity=car_sharing]

Still to be defined:
* Icons of each feature type
* Detail information to be displayed on click
* May be additional filter criteria, if unintended features (e.g. only private access) show up in the map

Digitransit documentation describes how to add GeoJSON layers.

Additional info:
* https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/GeoJson.md
* https://wiki.openstreetmap.org/ (general documentation about OSM / reference for tagging)
* https://overpass-turbo.eu (query engine)
* https://wiki.openstreetmap.org/wiki/Overpass_turbo (documentation)

**Comment by Beck-berry** [comment]
The GeoJson layer should be added in the config.hsl.js file.

**Comment by Beck-berry** [comment]
I made no modifications on the HB version of Digitransit however I constantly get SyntaxError in JSON and sometimes Source map error. (sockjs.js.map)
https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors#Invalid_source_map
* I changed ``` devtools: 'inline-map-source' ``` in webpack.config.babel.js which seems to solved the source map error (at least I don't get any notifications about it).

![hb_json_syntax_2019-09-19_11-33-52](https://user-images.githubusercontent.com/46535522/65232439-6dffa000-dad1-11e9-9ab0-6905fb780b11.png)
* I looked through the localStorage and the MapLayerStore JS files (both in app/store/) with the debugger but I didn't find the solution.
* I checked every default value given to the getItemAsJson function - they are valid. Since there is no stored data yet, every item have their default values, these are parsed.

I have no idea what causes the error.

**Comment by Beck-berry** [comment]
This is quite awkward, but this morning I ran the UI in a private browser window and it worked perfectly. Something must be wrong with Firefox or the plugins I have installed...

**Comment by Beck-berry** [comment]
[GeoJson docs](https://tools.ietf.org/html/rfc7946)

**Comment by Beck-berry** [comment]
When feature is a Point: name attribute is shown in the popup.
When feature is a MultiPoint: popupContent attribute is shown is the popup.

**Comment by Beck-berry** [comment]
@hbruch 
Do we have to be able to set these coordinates (for example a bike shop) as origin or destination?
