### ISSUE TITLE
Clean up bicycle safety factors

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#151]
In https://github.com/mfdz/digitransit-ui/commit/c734d62d84f8be2c55beaffc950dc14e3bc62140 I had to duplicate the settings for the bicycle safety factors because it seems that digitransit doesn't expect those values to be set in `config.hb.json`.

If you remove the stuff inside `triangle:{}` then the default setting does not work when you don't change anything.

If you remove the ones from one level up, then switching from "Avoid elevation changes" back to "Default settings" doesn't work as then there no more cycling factors to be sent to the server and it returns a 500.

On top of this, when you switch from "Avoid elevation changes" to "Default settings" then an extra `triangle=[object+Object]` is put into the URL, which should not be there.

To make matters worse, the server expects the bike factors to be inside a `triangle` object but in the URL they are top level parameters.

![Screenshot from 2020-04-23 14-49-30](https://user-images.githubusercontent.com/151346/80101830-3b8bb900-8572-11ea-9a7b-f781c712cde4.png)

It it's all very muddled. :man_shrugging: 

Acceptance criteria:

- Make it less of a mess, please. :)

**Comment by Beck-berry** [comment]
I deleted the triangle {} and the upper level factor initilizations from the config file, so as only the `optimize` variable remains as a default setting.
Then I updated the TRIANGLE factors in the /admin panel as follows:
![Screenshot_2020-04-24_10-45-28](https://user-images.githubusercontent.com/46535522/80193273-ca531100-8618-11ea-849f-5039c77ed521.png)
After saving the changes the difference was visible:
![Screenshot_2020-04-24_10-44-53](https://user-images.githubusercontent.com/46535522/80193445-1aca6e80-8619-11ea-98b4-04428a78396e.png)

However "Avoid changes in elevation" setting still causes problems.
When only change from "Default" to "Prefer cycleways", the url changes from TRIANGLE to GREENWAYS and vice versa, the map shows two partly different ways. But when "Avoid changes in elevation" is clicked, we see a third route but the selection jumps to "Default". So "Default", which showed a different route earlier, now cannot be chosen (unless first click on "prefer cycleways" and then "default").

**Comment by Beck-berry** [comment]
Another idea: if we'd like to use values as 
safetyFactor | 0.4
slopeFactor | 0.3
timeFactor | 0.3
why don't we initialize the default optimize setting as GREENWAYS?

**Comment by leonardehrenfried** [comment]
When you set it to GREENWAYS then the triangle factors are ignored and the route goes more through parks and other green areas.

**Comment by Beck-berry** [comment]
Ok, finally I found a good working solution: the default settings in the config.default should have been extended with the factors, without the `triangle` object.
I did not found out where exactly the `triangle` object gets created but trying to use it from the beginning as an object caused even more errors.

**Comment by Beck-berry** [comment]
Thing is, I found out that after switching back to 'default' the triangle factors were not replaced in the query, so I fixed that - this means after switch to 'default' the values are read from the defaultSettings. (This way no extra `triangle=[object+Object]` goes to the URL.)

Although this does not solve the problem of the start. Interesting, that I do not have the problem you described since I modified the triangle factors through the admin panel (and those values are sent first, not the defaultSettings from the config, I tried out different combinations). These settings are handled by the `localStorage.js` so we might should check what happens if we change the values. 'Local storage' says to me that is should be contained on the client side, but this admin panel is not advertised for the users, so how should they know how to set these values..? :thinking: You might want to check out the `AdminForm.js` too since I feel a bit lost on how to proceed with this right now.
