### ISSUE TITLE
Fix Covid19 icon's viewport

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#183]
The new icon for sports or outdoor shops has the wrong viewport again.

![Screenshot from 2020-05-08 13-46-40](https://user-images.githubusercontent.com/151346/81418116-771aab80-914c-11ea-9901-7d5732fbbf30.png)

<img width="115" alt="Screen Shot 2020-05-08 at 18 58 56" src="https://user-images.githubusercontent.com/151346/81429627-578c7e80-915e-11ea-85d9-0e4164b47490.png">

Please check all of them upstream, send them a PR and then merge it into our repo again.

**Comment by Beck-berry** [comment]
Sports icon is [already fixed by them](https://github.com/osmontrouge/caresteouvert/pull/693).
![Screenshot_2020-05-12_10-46-22](https://user-images.githubusercontent.com/46535522/81662433-d96df780-943d-11ea-8051-654b80a98e8e.png)

The issue with the shoes is a bit more difficult, since the resizing is done via a transform method in the `g` tag which we do not copy with the script. Solutions can be either to modify our script or send a PR without the transform attributes... I think the previous would work better since we cannot ask them to use a different aspect if it works well for them but not for us; and that way we would skip these kind of issues in the future. Do you agree?

**Comment by leonardehrenfried** [comment]
Yes, changing the aspect ratio is asking too much. If it's not too hard, then please change the script.

**Comment by Beck-berry** [comment]
Success!
![Screenshot_2020-05-13_10-32-35](https://user-images.githubusercontent.com/46535522/81790049-1cdf6900-9505-11ea-851b-b8d8549c6e6d.png)

**Comment by leonardehrenfried** [comment]
Nice, look forward to the PR.
