### ISSUE TITLE
Use hexagonal bus icon in trip overview

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#191]
We recently introduced hexagonal the bus icons for bus stops.

We would also like to have them in the trip overview:

![Screenshot from 2020-05-13 14-17-47](https://user-images.githubusercontent.com/151346/81811340-c41fc880-9524-11ea-878b-19637bda0a26.png)

**Comment by meromisi** [comment]
I couldn't make it work yet for only the origin and destination points. These points are created individually so it could be possible to modify only them the problem is (I think) that they are in a `<StopMarker>` tags where I couldn't set any prop (like `iconId`) to use exact icons. I think a solution might be to modify `StopMarker.js` to be able to set `iconId`  where needed and if its set it draws the icon instead of the circle. 
At the moment they look like this:
![image](https://user-images.githubusercontent.com/54352878/81922629-b0d03400-95dc-11ea-9c76-62dd3cd1170f.png)

**Comment by hbruch** [comment]
Only objection from my side is that the symbol overlaps the label. Is this the case today for the circle as well?

**Comment by meromisi** [comment]
No circles won't show if there's a label, as you can see on Leonard's screenshot at the beginning of the issue.

**Comment by hbruch** [comment]
Sorry, I don't understand. Your screenshot shows the bus station symbol on top of the 774 label. In the former screenshot, the label is placed at a different position where there is no stop, so it's rendering order is unclear.

**Comment by meromisi** [comment]
Sorry, you were right, circles do overlap labels at the moment. 
![image](https://user-images.githubusercontent.com/54352878/81952036-3fa57680-9606-11ea-90c7-aece04bbe3b1.png)

**Comment by meromisi** [comment]
Okay, it looks like this at the moment:
![image](https://user-images.githubusercontent.com/54352878/82025007-fea67400-9690-11ea-862f-2822cf33d7b8.png)
