### ISSUE TITLE
Run hb on OKD

### ISSUE THREAD

**Issue by meromisi** [mfdz/digitransit-ui#29]
[transportkollektiv's DockerHub](https://hub.docker.com/u/transportkollektiv)

- [x] build digitransit-ui docker image for our hb modifications
- [x] build own graphiql image OR use verschwoerhaus'
- [x] get photon pelias adapter image for hb (not important anymore)
- [ ] get app run via external IP [help](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
- [x]  build digitransit-ui docker image without layer data
- [x] build data-container docker image with layer data ([repo](https://github.com/mfdz/OpenTripPlanner-data-container/tree/hb_geojson_layers))
- [x] use the data-container to get the layer data

**Comment by meromisi** [comment]
I created docker image on dockerhub at this [link](https://cloud.docker.com/repository/docker/meromisi/digitransit-ui-hb)

**Comment by Beck-berry** [comment]
We have the [exact same issue](https://github.com/openshift/origin/issues/20773) when trying to create external IPs.

**Comment by Beck-berry** [comment]
[Docker image of data-container](https://hub.docker.com/r/beckberry/opentripplanner-data-container-hb)

**Comment by Beck-berry** [comment]
### Data container image
Changed the Dockerfile so now on the image creates the GeoJson files when the container starts running. However this new set up caused a new error.
![ovpasserror](https://user-images.githubusercontent.com/46535522/68190102-18158780-ffad-11e9-94bf-c3e909222500.png)

**Comment by Beck-berry** [comment]
### Add GeoJson layers to data-container-hb image
The geojson files should be added while preprocessing of the raw data, so a new gulp task had to be created. The task/generateGeoJSONLayers.js file pulls the data-tools image and runs the generation. Issues:
* logging into file does not work due to "file not found" error
* the geojson files are still generated into the docker container, however they should be generated into the local otp-data-container folder (volume is set)
* the generator task should be added to the preprocessing steps

Run the task:
```
$ DATA="`pwd`" ORG="beckberry" ROUTERS="hb"  BBOX="48.51592209023528,8.533287048339844,48.72607645125842,9.036598205566406" gulp genLayers
```
