### ISSUE TITLE
Install OKD

### ISSUE THREAD

**Issue by nandor-poka** [mfdz/digitransit-ui#4]
Install OKD (community edition of Kubernetes) and run it locally.
Estimate: 2h

Just so that it does not get forgotten: write deploy and teardown scripts.

**Comment by Beck-berry** [comment]
1. https://docs.okd.io/latest/getting_started/administrators.html#downloading-the-binary
2. Run in one terminal with: ```openshift start master```
3. Login in another terminal: ```$ oc login localhost:8443 --username=test --password=test```
4. https://docs.okd.io/latest/getting_started/administrators.html#try-it-out

It's all fine until this point but then I ask for the IP with ```oc status``` and open it in my browser and nothing displays. "The server is taking too long to respond."

**Comment by Beck-berry** [comment]
5. I had to add --insecure-registry=172.30.0.0/16 to the /lib/systemd/system/docker.service file. /* https://opensource.com/article/18/11/local-okd-cluster-linux , https://stackoverflow.com/questions/29430024/docker-registry-with-insecure-registry-and-docker-1-5 It was hard to find which file should be modified since all Linux distributions have different needs.*/
6. ```sudo apt-get install firewalld```
With ```oc cluster up``` --> unexpected error inspecting image openshift/origin-control-plane:v3.11
With openshift start master still got a blank page at https://127.0.0.1:8443.

**Comment by Beck-berry** [comment]
The problem was with docker permissions: you have to be added to the docker group to run ```oc cluster up``` properly.
So the last step to run OKD locally:
7. ```oc cluster up```
