### ISSUE TITLE
Add UI to add a carpool route

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/digitransit-ui#88]
We want to add a UI for adding carpool routes to digitransit. We've prepared some mockups which should act as an implementation guide.

In the car leg we see a button.
![Car Leg](https://user-images.githubusercontent.com/151346/76333998-c2524280-62f2-11ea-9fc9-0467fd24b847.png)

Translation: Fahrgemeinschaft anbieten/Offer carpool

Once clicked the right hand side opens a form where we usually display the routing settings.

## one-off
Here we see the form when the user has selected an one-off car pool route:
![Formular einmalig](https://user-images.githubusercontent.com/151346/76334005-c3836f80-62f2-11ea-8f9e-3ec9d2d3a648.png)

Translation:
```
Ihr Inserat

Abfahrt: {origin} um {departureTime}
Ankunft: {destination} um ca. {arrivalTime}

Wie oft bieten sie diese Fahrt an?

einmalig
regelmäßig

Jetzt inserieren
```
```
Your trip

Origin: {origin} at {departureTime}
Destination: {destination} at about. {arrivalTime}

How often do you want to add the offer?

once
recurring

Add now
```
## Recurring

When she selects a recurring route, we see the weekdays as individual choices.
![Formular regelmässig](https://user-images.githubusercontent.com/151346/76334016-c716f680-62f2-11ea-8b5d-fe7f4fef732c.png)
```
Ihr Inserat

Abfahrt: {origin} um {departureTime}
Ankunft: {destination} um ca. {arrivalTime}

Wie oft bieten sie diese Fahrt an?

einmalig
regelmäßig

Montag
Dienstag
Mittwoch
Donnerstag
Freitag
Samstag
Sonntag

Jetzt inserieren
```
```
Your offer

Origin: {origin} at {departureTime}
Destination: {destination} at about. {arrivalTime}

How often do you want to add the offer?

once
recurring

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday

Add now
```
## Complete

Once she is finished we see this.
![Inserat eingestellt](https://user-images.githubusercontent.com/151346/76334027-c9795080-62f2-11ea-80df-ee6f288416bb.png)
```
Vielen Dank

Ihr regelmäßiges/einmaliges Inserat von {origin} nach {destination} wurde eingestellt.

Sie haben die folgende Zeit (und Wochentage) inseriert:

{weekdays or date} um {time}.

Schlie­ßen
```
```
Thank you

Your one-off/recurring offer from {origin} to {destination} was added.

You've set the following time (and weekdays):

{weekdays or date} um {time}.

Schlie­ßen
```
Note: the backend is being completed as we speak but in the end of the flow we need to submit the following data to the server:

- origin
- destination
- date and time (if one off)
- time and weekdays (if recurring)
- phone number (this is not in the mockups, please add the form field and use your best judgement)

**Comment by meromisi** [comment]
I just wanted to simulate a travel by car to see the components and this happened not sure why does it want me to park the car and walk a lot to get to the destination. 
![car_route](https://user-images.githubusercontent.com/54352878/76317234-27e70480-62dc-11ea-84b6-ba352141274f.png)

**Comment by leonardehrenfried** [comment]
Can you double check that you're running the latest master?

I made a fix for this: https://github.com/mfdz/digitransit-ui/commit/19933d524960741ebe4c21dc1733626a442baad9

**Comment by leonardehrenfried** [comment]
And I think the reason it is trying to make you park is that the car icon means Park+Ride.

On top of this there is a main road in Herrenberg that is closed: https://www.openstreetmap.org/#map=18/48.59827/8.87022

**Comment by meromisi** [comment]
yes from master it works when I created the new branch it used an older version of the master, my mistake

**Comment by meromisi** [comment]
do you want it to look like a link or more like a button?
![car_travel_link2](https://user-images.githubusercontent.com/54352878/76323208-b3649380-62e4-11ea-8b2b-771e9fd77c4c.png)
![car_travel_link](https://user-images.githubusercontent.com/54352878/76323211-b3fd2a00-62e4-11ea-8ab9-1bcaee54bcb3.png)

**Comment by leonardehrenfried** [comment]
Button please.

**Comment by Beck-berry** [comment]
![Screenshot_2020-03-13_16-30-37](https://user-images.githubusercontent.com/46535522/76635706-2588e280-6548-11ea-8415-4f07df154b65.png)
![Screenshot_2020-03-13_16-31-10](https://user-images.githubusercontent.com/46535522/76635708-26217900-6548-11ea-9f9b-a001e146bd70.png)
![Screenshot_2020-03-13_16-31-25](https://user-images.githubusercontent.com/46535522/76635712-26ba0f80-6548-11ea-9723-181bee242963.png)

Yet time addition (in order to get the arrival time) is not perfectly managed. These screenshots are for your information about the state of the UI. :)

**Comment by hbruch** [comment]
Arrival / Departure time: I think, the backend currently only accepts the departure time, so no need to figure out the arrival time, if it's not already available.
Please try to avoid an update button. If the radio button is toggled, that should show / enable the weekday checkboxes.
Instead of showing/hiding the checkboxes, I prefer to show them always, but have them enabled/disabled depending on the once/regularly toggle.
If it's regularly, we write "Dienstags, ...", the "Am <date>" is for one-time offers.

Some corrections: "einmal"->"einmalig", "Schlißen"->"Schließen". "Next" -> "Inserieren", "Sie haben..." -> "Sie haben für den folgendes Datum/Uhrzeit inseriert:" (once);  "Sie haben für  folgende Zeit und Werktage inseriert:" (regular).

And for GDPR reasons, we'll need another checkbox wich is empty by default, but needs to be checked to enable the "Inserieren" button. Behing that checkbox, the following text should be displayed: "Ich habe die Datenschutzbestimmungen gelesen und erkläre mich einverstanden."

**Comment by Beck-berry** [comment]
![Képernyőkép – 2020-03-17 10-41-08](https://user-images.githubusercontent.com/46535522/76843448-18b40980-683c-11ea-918f-d8aba773de23.png)
![Képernyőkép – 2020-03-17 10-40-46](https://user-images.githubusercontent.com/46535522/76843454-19e53680-683c-11ea-8759-1618861c2813.png)
![Képernyőkép – 2020-03-17 10-40-21](https://user-images.githubusercontent.com/46535522/76843458-1a7dcd00-683c-11ea-8994-b4aaf51e2f08.png)

**Comment by leonardehrenfried** [comment]
Can you please add a label to the phone number field?

**Comment by leonardehrenfried** [comment]
And have you prepared the HTTP call to the backend? The API is specified here: https://github.com/mfdz/digitransit-ui/pull/94
